### PR TITLE
Fixed bugg where schema.format did not use param.

### LINKED ISSUE #42: Duns.format(value) does not work
Duns.format does not work when passing a value using format()

### PR DESCRIPTION
**Pull request by silfverstrom**
The following code did previously not work,

```
var schema = Duns.any().returns(function(num) {
  return num * 2;
});
schema.format(10); // Fails.

```

This was due to 'format' not accepting any params, and only using its
bound value.

This PR closes #42.

### CODE REVIEW

**Comment by silfverstrom** [comment]
ping @br0r

File: tests/any_validator_test.js [hunk 1]
```diff
@@ -132,4 +132,14 @@ describe('Duns - Any Validator', function() {
     should(Duns.validate('10', schema)).be.false;
   });
 
+  it('Can format value', function() {
+    var schema = Duns.any().returns(function(val) {
+      return val * 2;
+    });
+
+    should(schema.init(10).format(10)).be.eql(20);
```
Comment (br0r) [inline tests/any_validator_test.js]: Perhaps the init value should be changed to for example 5 or something. To illustrate that the `.format` has precedence.

Comment (silfverstrom) [inline tests/any_validator_test.js]: fair enough. I've updated the test to reflect the precedence of methods. @br0r
